### your site title here

title: Sabrina Amorim
description: Animal Breeding and Genetics | Data Analytics | Phenomics

baseurl: "/" #name of GitHub repository
url: "https://sabrinaam.github.io/" ##custom url to be used instead of GitHub repository
email: asabrina@vt.edu

# Pagination
paginate: 4
permalink: /blog/:year/:title/
paginate_path: /blog/page:num/

# Social media links in footer
twitter: "https://twitter.com/amorimsab"
linkedin: "https://www.linkedin.com/in/sabrina-amorim-9857a0bb"
#stackoverflow: "#"
github: "https://github.com/sabrinaam"
researchgate: "https://www.researchgate.net/profile/Sabrina-Amorim-2"
orcid: "https://orcid.org/0000-0003-4130-2040"



# Markdown
highlighter: rouge
markdown: kramdown

# Tracker
analytics:

# optimization -> compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

#collection
collections:
  projects:
    output: true
    permalink: /projects/:name/
    order:
      - shortProject.md
      - longerProjectTitle.md
      - redirect.md
      - project4.md
      - project5.md
      - project6.md

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

exclude:
  - README.md
  - LICENSE.md

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-email-protect
  - jekyll-target-blank
